// Shell: landing gate, masthead with schedule-aware tagline, tab nav, dev-mode toggle.
// Dev mode unlocks Dashboard + Console tabs and flips the theme via data-mode on <html>.
import { useEffect, useState } from 'react'
import Settings from './Settings'
import Episodes from './Episodes'
import Dashboard from './Dashboard'
import DevPanel from './DevPanel'
import Landing from './Landing'
import { api, type Preferences } from './api'

const WEEKDAYS = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']

function tagline(p: Preferences | null): string {
  if (!p || !p.schedule_enabled) return 'YOUR NEWS · YOUR HOSTS · ON DEMAND'
  const h = p.schedule_hour
  const daypart = h < 5 ? 'NIGHT' : h < 12 ? 'MORNING' : h < 17 ? 'AFTERNOON' : h < 21 ? 'EVENING' : 'NIGHT'
  const time = `${String(h).padStart(2, '0')}:${String(p.schedule_minute).padStart(2, '0')}`
  if (p.schedule_frequency === 'weekly')
    return `YOUR NEWS · YOUR HOSTS · EVERY ${WEEKDAYS[p.schedule_weekday]} AT ${time}`
  return `YOUR NEWS · YOUR HOSTS · EVERY ${daypart} AT ${time}`
}

export default function App() {
  const [dev, setDev] = useState(() => localStorage.getItem('devmode') === '1')
  const tabs = dev ? ['Episodes', 'Settings', 'Dashboard', 'Console'] : ['Episodes', 'Settings']
  const [tab, setTab] = useState('Episodes')
  const [prefs, setPrefs] = useState<Preferences | null>(null)
  // landing shows once per browser; ABOUT in the footer brings it back
  const [landing, setLanding] = useState(() => localStorage.getItem('visited') !== '1')

  const enterStudio = () => {
    localStorage.setItem('visited', '1')
    setLanding(false)
  }

  useEffect(() => {
    const load = () => api.getPreferences().then(setPrefs).catch(() => {})
    load()
    window.addEventListener('prefs-saved', load)
    return () => window.removeEventListener('prefs-saved', load)
  }, [])

  useEffect(() => {
    document.documentElement.dataset.mode = dev ? 'dev' : 'user'
    localStorage.setItem('devmode', dev ? '1' : '0')
    if (!dev && (tab === 'Dashboard' || tab === 'Console')) setTab('Episodes')
  }, [dev, tab])

  if (landing) return <Landing onEnter={enterStudio} />

  return (
    <div className="app">
      <header className="masthead">
        <div className="brand">
          <span className="onair mono">● ON AIR</span>
          <h1>News<em>Reel</em></h1>
          <p className="tagline mono">{tagline(prefs)}</p>
        </div>
        <div className="masthead-right">
          <nav className="tabs" aria-label="Sections">
            {tabs.map((t) => (
              <button key={t} className={`tab mono ${tab === t ? 'active' : ''}`} onClick={() => setTab(t)}>
                {t}
              </button>
            ))}
          </nav>
          <label className="devswitch mono" title="Developer mode: tuning, API keys, internal dashboard">
            <input type="checkbox" checked={dev} onChange={(e) => setDev(e.target.checked)} />
            <span className="devswitch-track" aria-hidden />
            DEV
          </label>
        </div>
      </header>
      <main>
        {tab === 'Episodes' && <Episodes dev={dev} />}
        {tab === 'Settings' && <Settings />}
        {tab === 'Dashboard' && dev && <Dashboard />}
        {tab === 'Console' && dev && <DevPanel />}
      </main>
      <footer className="mono">
        EST. 2026 · GENERATED BY ROBOTS, CURATED BY YOU ·{' '}
        <button className="linklike mono" onClick={() => setLanding(true)}>ABOUT</button>
      </footer>
    </div>
  )
}
